Social\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        path:
            type: string

    manyToMany:
        friendsWithMe:
            targetEntity: User
            mappedBy: myFriends

        myFriends:
            targetEntity: User
            inversedBy: friendsWithMe
            joinTable:
                name: friends
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    friends_user_id:
                        referencedColumnName: id