social_user_list:
    pattern: /users
    defaults: {_controller: SocialSearchUserBundle:Search:index}
social_redirect:
    pattern: /redirectUSer/{id}/{path}/{username}
    defaults: {_controller: SocialSearchUserBundle:Search:redirect}