social_contact_list:
    pattern:  /
    defaults: { _controller: SocialContactBundle:Default:index }

social_contact_list_add:
    requirements:
        _method: POST
    pattern: /add
    defaults: { _controller: SocialContactBundle:Default:add }

social_contact_list_delete:
    requirements:
        _method: POST
    pattern: /delete
    defaults: { _controller: SocialContactBundle:Default:delete }