parameters:
#    social_contact.example.class: Social\ContactBundle\Example

services:
#    social_contact.example:
#        class: %social_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
