parameters:
#    social_avatar.example.class: Social\AvatarBundle\Example

services:
#    social_avatar.example:
#        class: %social_avatar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
