Social\PhotoBundle\Entity\Album:
    type: entity
    table: album
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        date:
            type: datetime
        auteur:
            type: integer

    lifecycleCallbacks: {  }
